version: "3"

name: sonarqube

services:
  db:
    image: postgres:16.2-alpine3.19
    user: root
    restart: no
    hostname: sonarqube-db
    shm_size: 2gb
    mem_limit: 2gb
    cpus: 1
    #mem_reservation: 1024M
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=Etc/UTC
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./data/sonarqube-db:/var/lib/postgresql/data
      - ./sonarqube_postgres_init.sql:/docker-entrypoint-initdb.d/sonarqube_postgres_init.sql

  sonarqube:
    image: sonarqube:10.4.1-community
    restart: no
    hostname: sonarqube
    shm_size: 2gb
    mem_limit: 2gb
    cpus: 1
    depends_on:
      - db
    environment:
      SONAR_EDITION: community
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db/sonarqube
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/sonarqube/data:/opt/sonarqube/data
      - ./data/sonarqube/logs:/opt/sonarqube/logs
      - ./data/sonarqube/extensions:/opt/sonarqube/extensions

    ports:
      - "9000:9000"

networks:
  default:
    name: sonarqube-net
