version: "3"

name: scratch-dbs

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04
    user: root
    restart: no
    hostname: scratch-mssql
    shm_size: 1gb
    environment:
      # https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD} # Set in env file
      - MSSQL_PID=Developer # i.e. all features, but licensed for dev/test only
      - MSSQL_AGENT_ENABLED=0
      - MSSQL_ENABLE_HADR=0 # High Availability & Disaster Recovery
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backups
      - MSSQL_LCID=1033 # English
      #- MSSQL_MEMORY_LIMIT_MB=1024
      - TZ=Etc/UTC # https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-configure-time-zone
    ports:
      - 14330:1433
    volumes:
      # You can't map to the root of the container, so we map to the subdirectories
      - ./data/mssql/backups:/var/opt/mssql/backups
      - ./data/mssql/data:/var/opt/mssql/data

networks:
  default:
    name: scratch-dbs-net
