version: "3"

name: scratch-dbs

services:
  redis:
    image: redis:7.2.4-alpine3.19
    user: root
    restart: no
    hostname: scratch-redis
    shm_size: 1gb
    environment:
      - REDIS_PASSWORD=${DB_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    ports:
      - "63790:6379"
    volumes:
      - ./data/redis:/data

networks:
  default:
    name: scratch-dbs-net
