name: scratch-azurite

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    restart: no
    hostname: scratch-azurite
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - TZ=Etc/UTC
    # https://github.com/Azure/Azurite?tab=readme-ov-file#supported-command-line-options
    command: >
      /bin/ash -c "
      azurite
      --blobHost 0.0.0.0
      --blobPort 10000
      --queueHost 0.0.0.0
      --queuePort 10001
      --tableHost 0.0.0.0
      --tablePort 10002
      --location /data
      --debug /data/debug.log
      ;
      "
    ports:
      - "10000:10000" # default blob storage port
      - "10001:10001" # default queue storage port
      - "10002:10002" # default table storage port
    volumes:
      - ./data/azurite:/data

networks:
  default:
    name: scratch-azurite-net
