name: scratch-postgres

services:
  postgresql:
    image: postgres:16.2-alpine3.19
    restart: no
    hostname: scratch-postgresql
    shm_size: 1gb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=Etc/UTC
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 54320:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

networks:
  default:
    name: scratch-postgres-net
